/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_shiftleft_35 (
    input [15:0] a,
    input [3:0] b,
    output reg [15:0] q
  );
  
  
  
  reg [15:0] w;
  
  reg [15:0] x;
  
  reg [15:0] y;
  
  always @* begin
    
    case (b[3+0-:1])
      1'h0: begin
        w = a;
      end
      1'h1: begin
        w[8+7-:8] = a[0+7-:8];
        w[0+7-:8] = 8'h00;
      end
      default: begin
        w = a;
      end
    endcase
    
    case (b[2+0-:1])
      1'h0: begin
        x = w;
      end
      1'h1: begin
        x[4+11-:12] = w[0+11-:12];
        x[0+3-:4] = 4'h0;
      end
      default: begin
        x = w;
      end
    endcase
    
    case (b[1+0-:1])
      1'h0: begin
        y = x;
      end
      1'h1: begin
        y[2+13-:14] = x[0+13-:14];
        y[0+1-:2] = 2'h0;
      end
      default: begin
        y = x;
      end
    endcase
    
    case (b[0+0-:1])
      1'h0: begin
        q = y;
      end
      1'h1: begin
        q[1+14-:15] = y[0+14-:15];
        q[0+0-:1] = 1'h0;
      end
      default: begin
        q = y;
      end
    endcase
  end
endmodule
