/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module basket_fsm_4 (
    input clk,
    input rst,
    input l,
    input r,
    input c,
    output reg [7:0] q,
    output reg [2:0] state
  );
  
  
  
  localparam ABLUE_basket = 3'd0;
  localparam ARED_basket = 3'd1;
  localparam BBLUE_basket = 3'd2;
  localparam BRED_basket = 3'd3;
  localparam CBLUE_basket = 3'd4;
  localparam CRED_basket = 3'd5;
  localparam DBLUE_basket = 3'd6;
  localparam DRED_basket = 3'd7;
  
  reg [2:0] M_basket_d, M_basket_q = ABLUE_basket;
  
  always @* begin
    M_basket_d = M_basket_q;
    
    q = 8'h00;
    
    case (M_basket_q)
      ABLUE_basket: begin
        q = 8'h80;
        state = 1'h1;
        if (r) begin
          M_basket_d = BBLUE_basket;
        end else begin
          if (l) begin
            M_basket_d = DBLUE_basket;
          end else begin
            if (c) begin
              M_basket_d = ARED_basket;
            end
          end
        end
      end
      ARED_basket: begin
        q = 8'h40;
        state = 2'h2;
        if (r) begin
          M_basket_d = BRED_basket;
        end
        if (l) begin
          M_basket_d = DRED_basket;
        end else begin
          if (c) begin
            M_basket_d = ABLUE_basket;
          end
        end
      end
      BBLUE_basket: begin
        q = 8'h20;
        state = 2'h3;
        if (l) begin
          M_basket_d = ABLUE_basket;
        end else begin
          if (r) begin
            M_basket_d = CBLUE_basket;
          end else begin
            if (c) begin
              M_basket_d = BRED_basket;
            end
          end
        end
      end
      BRED_basket: begin
        q = 8'h10;
        state = 3'h4;
        if (l) begin
          M_basket_d = ARED_basket;
        end else begin
          if (r) begin
            M_basket_d = CRED_basket;
          end else begin
            if (c) begin
              M_basket_d = BBLUE_basket;
            end
          end
        end
      end
      CBLUE_basket: begin
        q = 8'h08;
        state = 3'h5;
        if (l) begin
          M_basket_d = BBLUE_basket;
        end else begin
          if (r) begin
            M_basket_d = DBLUE_basket;
          end else begin
            if (c) begin
              M_basket_d = CRED_basket;
            end
          end
        end
      end
      CRED_basket: begin
        q = 8'h04;
        state = 3'h6;
        if (l) begin
          M_basket_d = BRED_basket;
        end else begin
          if (r) begin
            M_basket_d = DRED_basket;
          end else begin
            if (c) begin
              M_basket_d = CBLUE_basket;
            end
          end
        end
      end
      DBLUE_basket: begin
        q = 8'h02;
        state = 3'h7;
        if (l) begin
          M_basket_d = CBLUE_basket;
        end else begin
          if (r) begin
            M_basket_d = ABLUE_basket;
          end else begin
            if (c) begin
              M_basket_d = DRED_basket;
            end
          end
        end
      end
      DRED_basket: begin
        q = 8'h01;
        state = 4'h8;
        if (l) begin
          M_basket_d = CRED_basket;
        end
        if (r) begin
          M_basket_d = ARED_basket;
        end else begin
          if (c) begin
            M_basket_d = DBLUE_basket;
          end
        end
      end
      default: begin
        M_basket_d = ABLUE_basket;
        state = 1'h0;
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_basket_q <= 1'h0;
    end else begin
      M_basket_q <= M_basket_d;
    end
  end
  
endmodule
