/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module bin_to_led_2 (
    input [1:0] deci,
    output reg [2:0] threebit
  );
  
  
  
  always @* begin
    
    case (deci)
      1'h0: begin
        threebit = 3'h0;
      end
      1'h1: begin
        threebit = 3'h1;
      end
      2'h2: begin
        threebit = 3'h3;
      end
      2'h3: begin
        threebit = 3'h7;
      end
      default: begin
        threebit = 3'h0;
      end
    endcase
  end
endmodule
