/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module seven_segment_30 (
    input [3:0] char,
    output reg [7:0] segs
  );
  
  
  
  always @* begin
    
    case (char)
      1'h0: begin
        segs = 8'h14;
      end
      1'h1: begin
        segs = 8'hd7;
      end
      2'h2: begin
        segs = 8'h4c;
      end
      2'h3: begin
        segs = 8'h45;
      end
      3'h4: begin
        segs = 8'h87;
      end
      3'h5: begin
        segs = 8'h25;
      end
      3'h6: begin
        segs = 8'h24;
      end
      3'h7: begin
        segs = 8'h57;
      end
      4'h8: begin
        segs = 8'h04;
      end
      4'h9: begin
        segs = 8'h05;
      end
      default: begin
        segs = 8'h00;
      end
    endcase
  end
endmodule
