/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_shiftright_mux_29 (
    input a,
    input alufn1,
    output reg out
  );
  
  
  
  always @* begin
    
    case (alufn1)
      1'h0: begin
        out = 1'h0;
      end
      1'h1: begin
        out = a;
      end
      default: begin
        out = 1'h0;
      end
    endcase
  end
endmodule
