/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module main_fsm_4 (
    input clk,
    input rst,
    input start,
    input [15:0] rd2,
    input [15:0] cycleCounter,
    input hold,
    input clkHold,
    output reg [1:0] asel,
    output reg [2:0] bsel,
    output reg [5:0] alufn,
    output reg stu,
    output reg we,
    output reg [3:0] ra,
    output reg [3:0] rb,
    output reg [3:0] rc
  );
  
  
  
  localparam INITLIFE_state = 6'd0;
  localparam INCREASECOUNT_state = 6'd1;
  localparam SHIFTBLOCK1_state = 6'd2;
  localparam SHIFTBLOCK2_state = 6'd3;
  localparam SHIFTBLOCK3_state = 6'd4;
  localparam SHIFTBLOCK4_state = 6'd5;
  localparam RANDCOL_state = 6'd6;
  localparam CHECKCOL_state = 6'd7;
  localparam BRANCHCOL_state = 6'd8;
  localparam RANDCOLOUR_state = 6'd9;
  localparam ADDCOLOR1_state = 6'd10;
  localparam ADDCOLOR2_state = 6'd11;
  localparam ADDBLOCK_state = 6'd12;
  localparam STORECOL1_state = 6'd13;
  localparam STORECOL2_state = 6'd14;
  localparam STORECOL3_state = 6'd15;
  localparam STORECOL4_state = 6'd16;
  localparam CHECKEMPTYROW_state = 6'd17;
  localparam BRANCHEMPTYROW_state = 6'd18;
  localparam CHECKPLAYERPOS_state = 6'd19;
  localparam BRANCHSCORE_state = 6'd20;
  localparam CHECKCOMBO_state = 6'd21;
  localparam ADDCOMBO_state = 6'd22;
  localparam MULCOMBO_state = 6'd23;
  localparam ADDSCORE_state = 6'd24;
  localparam RESETCOMBO_state = 6'd25;
  localparam MINUSHEALTH_state = 6'd26;
  localparam CHECKHEALTH_state = 6'd27;
  localparam BRANCHHEALTH_state = 6'd28;
  localparam COUNTERMOD_state = 6'd29;
  localparam CHECKMOD_state = 6'd30;
  localparam BRANCHMOD_state = 6'd31;
  localparam INCREASECLK_state = 6'd32;
  localparam CLKHOLD_state = 6'd33;
  localparam END_state = 6'd34;
  localparam IDLE_state = 6'd35;
  
  reg [5:0] M_state_d, M_state_q = INITLIFE_state;
  wire [1-1:0] M_slowClock_value;
  counter_16 slowClock (
    .clk(clk),
    .rst(rst),
    .value(M_slowClock_value)
  );
  wire [1-1:0] M_slowClock1_value;
  counter_17 slowClock1 (
    .clk(clk),
    .rst(rst),
    .value(M_slowClock1_value)
  );
  wire [1-1:0] M_slowClock2_value;
  counter_18 slowClock2 (
    .clk(clk),
    .rst(rst),
    .value(M_slowClock2_value)
  );
  wire [1-1:0] M_slowClock3_value;
  counter_19 slowClock3 (
    .clk(clk),
    .rst(rst),
    .value(M_slowClock3_value)
  );
  wire [1-1:0] M_slowClock4_value;
  counter_20 slowClock4 (
    .clk(clk),
    .rst(rst),
    .value(M_slowClock4_value)
  );
  wire [1-1:0] M_slowClockEdge_out;
  reg [1-1:0] M_slowClockEdge_in;
  edge_detector_8 slowClockEdge (
    .clk(clk),
    .in(M_slowClockEdge_in),
    .out(M_slowClockEdge_out)
  );
  wire [1-1:0] M_slowClockEdge1_out;
  reg [1-1:0] M_slowClockEdge1_in;
  edge_detector_8 slowClockEdge1 (
    .clk(clk),
    .in(M_slowClockEdge1_in),
    .out(M_slowClockEdge1_out)
  );
  wire [1-1:0] M_slowClockEdge2_out;
  reg [1-1:0] M_slowClockEdge2_in;
  edge_detector_8 slowClockEdge2 (
    .clk(clk),
    .in(M_slowClockEdge2_in),
    .out(M_slowClockEdge2_out)
  );
  wire [1-1:0] M_slowClockEdge3_out;
  reg [1-1:0] M_slowClockEdge3_in;
  edge_detector_8 slowClockEdge3 (
    .clk(clk),
    .in(M_slowClockEdge3_in),
    .out(M_slowClockEdge3_out)
  );
  wire [1-1:0] M_slowClockEdge4_out;
  reg [1-1:0] M_slowClockEdge4_in;
  edge_detector_8 slowClockEdge4 (
    .clk(clk),
    .in(M_slowClockEdge4_in),
    .out(M_slowClockEdge4_out)
  );
  
  always @* begin
    M_state_d = M_state_q;
    
    M_slowClockEdge_in = M_slowClock_value;
    M_slowClockEdge1_in = M_slowClock1_value;
    M_slowClockEdge2_in = M_slowClock2_value;
    M_slowClockEdge3_in = M_slowClock3_value;
    M_slowClockEdge4_in = M_slowClock4_value;
    asel = 2'h0;
    bsel = 3'h0;
    stu = 1'h0;
    we = 1'h0;
    ra = 4'h0;
    rb = 4'h0;
    rc = 4'h0;
    alufn = 6'h00;
    
    case (M_state_q)
      IDLE_state: begin
        if (start) begin
          M_state_d = INITLIFE_state;
        end
      end
      INITLIFE_state: begin
        alufn = 6'h00;
        ra = 4'h6;
        rc = 4'h6;
        asel = 2'h0;
        bsel = 3'h3;
        if (M_slowClockEdge_out == 1'h1) begin
          if (clkHold == 1'h0) begin
            M_state_d = INCREASECOUNT_state;
          end
        end
      end
      INCREASECOUNT_state: begin
        alufn = 6'h00;
        ra = 4'h7;
        rc = 4'h7;
        asel = 2'h0;
        bsel = 3'h1;
        if (M_slowClockEdge_out == 1'h1) begin
          if (clkHold == 1'h0) begin
            M_state_d = SHIFTBLOCK1_state;
          end
        end
      end
      SHIFTBLOCK1_state: begin
        alufn = 6'h20;
        ra = 4'h0;
        rc = 4'h0;
        asel = 2'h0;
        bsel = 3'h2;
        if (M_slowClockEdge_out == 1'h1) begin
          if (clkHold == 1'h0) begin
            M_state_d = SHIFTBLOCK2_state;
          end
        end
      end
      SHIFTBLOCK2_state: begin
        alufn = 6'h20;
        ra = 4'h1;
        rc = 4'h1;
        asel = 2'h0;
        bsel = 3'h2;
        if (M_slowClockEdge_out == 1'h1) begin
          if (clkHold == 1'h0) begin
            M_state_d = SHIFTBLOCK3_state;
          end
        end
      end
      SHIFTBLOCK3_state: begin
        alufn = 6'h20;
        ra = 4'h1;
        rc = 4'h1;
        asel = 2'h0;
        bsel = 3'h2;
        we = 1'h1;
        if (M_slowClockEdge_out == 1'h1) begin
          if (clkHold == 1'h0) begin
            M_state_d = SHIFTBLOCK4_state;
          end
        end
      end
      SHIFTBLOCK4_state: begin
        alufn = 6'h20;
        ra = 4'h1;
        rc = 4'h1;
        asel = 2'h0;
        bsel = 3'h2;
        we = 1'h1;
        if (M_slowClockEdge_out) begin
          if (clkHold == 1'h0) begin
            M_state_d = RANDCOL_state;
          end
        end
      end
      RANDCOL_state: begin
        alufn = 6'h1c;
        rc = 4'h9;
        asel = 2'h3;
        we = 1'h1;
        if (M_slowClockEdge_out) begin
          if (clkHold == 1'h0) begin
            M_state_d = CHECKCOL_state;
          end
        end
      end
      CHECKCOL_state: begin
        alufn = 6'h37;
        ra = 4'h9;
        rc = 4'hb;
        asel = 2'h0;
        bsel = 3'h3;
        we = 1'h1;
        if (M_slowClockEdge_out) begin
          if (clkHold == 1'h0) begin
            M_state_d = BRANCHCOL_state;
          end
        end
      end
      BRANCHCOL_state: begin
        rb = 4'hb;
        we = 1'h0;
        if (rd2 == 16'h0001) begin
          if (M_slowClockEdge_out) begin
            if (clkHold == 1'h0) begin
              M_state_d = RANDCOLOUR_state;
            end
          end
        end else begin
          if (M_slowClockEdge_out) begin
            if (clkHold == 1'h0) begin
              M_state_d = STORECOL1_state;
            end
          end
        end
      end
      RANDCOLOUR_state: begin
        alufn = 6'h1c;
        bsel = 3'h6;
        rc = 4'ha;
        we = 1'h1;
        if (M_slowClockEdge_out) begin
          if (clkHold == 1'h0) begin
            M_state_d = ADDCOLOR1_state;
          end
        end
      end
      ADDCOLOR1_state: begin
        alufn = 6'h1c;
        bsel = 3'h0;
        rb = 8'h09;
        rc = 8'h0b;
        we = 1'h1;
        if (M_slowClockEdge_out) begin
          if (clkHold == 1'h0) begin
            M_state_d = ADDCOLOR2_state;
          end
        end
      end
      ADDCOLOR2_state: begin
        alufn = 6'h00;
        asel = 1'h0;
        bsel = 3'h0;
        ra = 8'h0a;
        rb = 8'h0b;
        rc = 8'h0c;
        we = 1'h1;
        if (M_slowClockEdge_out) begin
          if (clkHold == 1'h0) begin
            M_state_d = ADDBLOCK_state;
          end
        end
      end
      ADDBLOCK_state: begin
        alufn = 6'h1c;
        bsel = 3'h0;
        rb = 8'h0c;
        if (rd2 == 1'h0) begin
          rc = 1'h0;
        end else begin
          if (rd2 == 1'h1) begin
            rc = 2'h1;
          end else begin
            if (rd2 == 2'h2) begin
              rc = 2'h2;
            end else begin
              if (rd2 == 2'h3) begin
                rc = 2'h3;
              end
            end
          end
        end
        we = 1'h1;
        if (M_slowClockEdge_out) begin
          if (clkHold == 1'h0) begin
            M_state_d = BRANCHCOL_state;
          end
        end
      end
      STORECOL1_state: begin
        alufn = 6'h38;
        asel = 2'h0;
        bsel = 3'h4;
        ra = 4'h0;
        rc = 4'h8;
        if (M_slowClockEdge_out) begin
          if (clkHold == 1'h0) begin
            M_state_d = STORECOL2_state;
          end
        end
      end
      STORECOL2_state: begin
        alufn = 6'h39;
        asel = 2'h0;
        bsel = 3'h0;
        ra = 4'h1;
        rb = 4'h8;
        rc = 4'h8;
        if (M_slowClockEdge_out) begin
          if (clkHold == 1'h0) begin
            M_state_d = STORECOL3_state;
          end
        end
      end
      STORECOL3_state: begin
        alufn = 6'h3a;
        asel = 2'h0;
        bsel = 3'h0;
        ra = 4'h2;
        rb = 4'h8;
        rc = 4'h8;
        if (M_slowClockEdge_out) begin
          if (clkHold == 1'h0) begin
            M_state_d = STORECOL4_state;
          end
        end
      end
      STORECOL4_state: begin
        alufn = 6'h3b;
        asel = 2'h0;
        bsel = 3'h0;
        ra = 4'h3;
        rb = 4'h8;
        rc = 4'h8;
        if (M_slowClockEdge_out) begin
          if (clkHold == 1'h0) begin
            M_state_d = CHECKEMPTYROW_state;
          end
        end
      end
      CHECKEMPTYROW_state: begin
        alufn = 6'h33;
        ra = 4'hd;
        rc = 4'h7;
        asel = 2'h2;
        bsel = 3'h5;
        we = 1'h1;
        if (M_slowClockEdge_out) begin
          if (clkHold == 1'h0) begin
            M_state_d = BRANCHEMPTYROW_state;
          end
        end
      end
      BRANCHEMPTYROW_state: begin
        rb = 4'h7;
        we = 1'h0;
        if (rd2 == 16'h0001) begin
          if (M_slowClockEdge_out) begin
            if (clkHold == 1'h0) begin
              M_state_d = COUNTERMOD_state;
            end
          end
        end else begin
          if (M_slowClockEdge_out) begin
            if (clkHold == 1'h0) begin
              M_state_d = CHECKPLAYERPOS_state;
            end
          end
        end
      end
      CHECKPLAYERPOS_state: begin
        alufn = 6'h33;
        ra = 4'h8;
        rc = 4'hc;
        asel = 2'h0;
        bsel = 3'h5;
        we = 1'h1;
        if (M_slowClockEdge_out) begin
          if (clkHold == 1'h0) begin
            M_state_d = BRANCHSCORE_state;
          end
        end
      end
      BRANCHSCORE_state: begin
        rb = 4'hc;
        we = 1'h0;
        if (rd2 == 16'h0001) begin
          if (M_slowClockEdge_out) begin
            if (clkHold == 1'h0) begin
              M_state_d = CHECKCOMBO_state;
            end
          end
        end else begin
          if (M_slowClockEdge_out) begin
            if (clkHold == 1'h0) begin
              M_state_d = RESETCOMBO_state;
            end
          end
        end
      end
      CHECKCOMBO_state: begin
        alufn = 6'h33;
        ra = 4'h4;
        rc = 4'hc;
        asel = 2'h0;
        bsel = 3'h3;
        we = 1'h1;
        if (M_slowClockEdge_out) begin
          if (clkHold == 1'h0) begin
            M_state_d = ADDCOMBO_state;
          end
        end
      end
      ADDCOMBO_state: begin
        alufn = 6'h00;
        ra = 4'h4;
        rc = 4'h4;
        asel = 2'h0;
        bsel = 3'h1;
        we = 1'h1;
        if (M_slowClockEdge_out) begin
          if (clkHold == 1'h0) begin
            M_state_d = MULCOMBO_state;
          end
        end
      end
      MULCOMBO_state: begin
        alufn = 6'h20;
        ra = 4'h4;
        rc = 4'hd;
        asel = 2'h0;
        bsel = 3'h1;
        we = 1'h1;
        if (M_slowClockEdge_out) begin
          if (clkHold == 1'h0) begin
            M_state_d = ADDSCORE_state;
          end
        end
      end
      ADDSCORE_state: begin
        alufn = 6'h20;
        ra = 4'h5;
        rc = 4'h5;
        asel = 2'h0;
        bsel = 3'h0;
        we = 1'h1;
        if (M_slowClockEdge_out) begin
          if (clkHold == 1'h0) begin
            M_state_d = RESETCOMBO_state;
          end
        end
      end
      RESETCOMBO_state: begin
        alufn = 6'h20;
        ra = 4'h0;
        rc = 4'h4;
        asel = 2'h2;
        bsel = 3'h4;
        we = 1'h1;
        if (M_slowClockEdge_out) begin
          if (clkHold == 1'h0) begin
            M_state_d = MINUSHEALTH_state;
          end
        end
      end
      MINUSHEALTH_state: begin
        alufn = 6'h01;
        ra = 4'h6;
        rc = 4'h6;
        asel = 2'h0;
        bsel = 3'h1;
        we = 1'h1;
        if (M_slowClockEdge_out) begin
          if (clkHold == 1'h0) begin
            M_state_d = CHECKHEALTH_state;
          end
        end
      end
      CHECKHEALTH_state: begin
        alufn = 6'h37;
        ra = 4'h6;
        rc = 4'hd;
        asel = 2'h0;
        bsel = 3'h4;
        we = 1'h1;
        if (M_slowClockEdge_out) begin
          if (clkHold == 1'h0) begin
            M_state_d = BRANCHHEALTH_state;
          end
        end
      end
      BRANCHHEALTH_state: begin
        rb = 4'hd;
        we = 1'h0;
        if (rd2 == 16'h0001) begin
          if (M_slowClockEdge_out) begin
            if (clkHold == 1'h0) begin
              M_state_d = END_state;
            end
          end
        end else begin
          if (M_slowClockEdge_out) begin
            if (clkHold == 1'h0) begin
              M_state_d = COUNTERMOD_state;
            end
          end
        end
      end
      COUNTERMOD_state: begin
        alufn = 6'h3f;
        ra = 4'h7;
        rc = 4'he;
        asel = 2'h0;
        bsel = 3'h7;
        if (M_slowClockEdge_out) begin
          if (clkHold == 1'h0) begin
            M_state_d = CHECKMOD_state;
          end
        end
      end
      CHECKMOD_state: begin
        alufn = 6'h33;
        ra = 4'he;
        rc = 4'he;
        asel = 2'h0;
        bsel = 3'h4;
        we = 1'h1;
        if (M_slowClockEdge_out) begin
          if (clkHold == 1'h0) begin
            M_state_d = INCREASECLK_state;
          end
        end
      end
      BRANCHMOD_state: begin
        rb = 4'he;
        we = 1'h0;
        if (rd2 == 16'h0000) begin
          if (M_slowClockEdge_out) begin
            if (clkHold == 1'h0) begin
              M_state_d = INCREASECLK_state;
            end
          end
        end else begin
          if (M_slowClockEdge_out) begin
            if (clkHold == 1'h0) begin
              M_state_d = CLKHOLD_state;
            end
          end
        end
      end
      INCREASECLK_state: begin
        stu = 1'h1;
        if (M_slowClockEdge_out) begin
          if (clkHold == 1'h0) begin
            M_state_d = CLKHOLD_state;
          end
        end
      end
      CLKHOLD_state: begin
        if (hold) begin
          if (cycleCounter <= 4'ha) begin
            if (M_slowClockEdge_out) begin
              if (clkHold == 1'h0) begin
                M_state_d = INCREASECOUNT_state;
              end
            end
          end else begin
            if (cycleCounter <= 5'h1e) begin
              if (M_slowClockEdge1_out) begin
                if (clkHold == 1'h0) begin
                  M_state_d = INCREASECOUNT_state;
                end
              end
            end else begin
              if (cycleCounter <= 7'h46) begin
                if (M_slowClockEdge2_out) begin
                  if (clkHold == 1'h0) begin
                    M_state_d = INCREASECOUNT_state;
                  end
                end
              end else begin
                if (cycleCounter <= 8'h96) begin
                  if (M_slowClockEdge3_out) begin
                    if (clkHold == 1'h0) begin
                      M_state_d = INCREASECOUNT_state;
                    end
                  end
                end else begin
                  if (cycleCounter > 8'h96) begin
                    if (M_slowClockEdge4_out) begin
                      if (clkHold == 1'h0) begin
                        M_state_d = INCREASECOUNT_state;
                      end
                    end
                  end
                end
              end
            end
          end
        end
      end
      END_state: begin
        if (M_slowClockEdge_out) begin
          if (clkHold == 1'h0) begin
            M_state_d = IDLE_state;
          end
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_state_q <= 1'h0;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
endmodule
