/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_adder_XB_34 (
    input [15:0] b,
    input alufn0,
    output reg [15:0] xb
  );
  
  
  
  always @* begin
    xb[15+0-:1] = b[15+0-:1] ^ alufn0;
    xb[14+0-:1] = b[14+0-:1] ^ alufn0;
    xb[13+0-:1] = b[13+0-:1] ^ alufn0;
    xb[12+0-:1] = b[12+0-:1] ^ alufn0;
    xb[11+0-:1] = b[11+0-:1] ^ alufn0;
    xb[10+0-:1] = b[10+0-:1] ^ alufn0;
    xb[9+0-:1] = b[9+0-:1] ^ alufn0;
    xb[8+0-:1] = b[8+0-:1] ^ alufn0;
    xb[7+0-:1] = b[7+0-:1] ^ alufn0;
    xb[6+0-:1] = b[6+0-:1] ^ alufn0;
    xb[5+0-:1] = b[5+0-:1] ^ alufn0;
    xb[4+0-:1] = b[4+0-:1] ^ alufn0;
    xb[3+0-:1] = b[3+0-:1] ^ alufn0;
    xb[2+0-:1] = b[2+0-:1] ^ alufn0;
    xb[1+0-:1] = b[1+0-:1] ^ alufn0;
    xb[0+0-:1] = b[0+0-:1] ^ alufn0;
  end
endmodule
