/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_cmp_17 (
    input alufn2,
    input alufn1,
    input z,
    input v,
    input n,
    output reg [15:0] q
  );
  
  
  
  reg p;
  
  reg r;
  
  always @* begin
    p = v ^ n;
    r = p | z;
    
    case ({alufn2, alufn1})
      2'h1: begin
        q[0+0-:1] = z;
      end
      2'h2: begin
        q[0+0-:1] = p;
      end
      2'h3: begin
        q[0+0-:1] = r;
      end
    endcase
    q[1+14-:15] = 1'h0;
  end
endmodule
